### ISSUE TITLE
Multiple selections in donut chart

### ISSUE THREAD

**Issue by anukiransolur** [jettro/c3-angular-directive#100]
Is it possible to select multiple segments of donuts and then update the data? I have to filter the data based on selecting a segment in donut and I want to give the user an option to select two segments by clicking on each of them and then fire the update event. Appreciate your help.

**Comment by jettro** [comment]
Need to do a bit more research, but this could be what you need:
http://c3js.org/reference.html#data-selection-multiple

**Comment by jettro** [comment]
I added the directive, if you still need it, you can give it a spin. The example is in the donut example.

**Comment by anukiransolur** [comment]
Thanks a lot.
