### ISSUE TITLE
chart-grid-optional grid-class ?

### ISSUE THREAD

**Issue by jtaylor1022** [jettro/c3-angular-directive#102]
I'd like to apply custom styling to my optional grid lines, but I notice that while the axis, value and text properties have been implemented (http://jettro.github.io/c3-angular-directive/api-docs/1.0/chartGridOptional.html) there's not one for class. I'd like to be able to style individual optional grid lines without changing the entire grid. Is this possible currently, or could you please add this option to the chart-grid-optional directive?

**Comment by jettro** [comment]
Added more properties to the gridOptional directive. Added the class and the position attribute.
