### ISSUE TITLE
How do I use gridClass with chart-grid-optional?

### ISSUE THREAD

**Issue by jtaylor1022** [jettro/c3-angular-directive#109]
I'm trying to add an optional grid line to my chart, and style it. I think I'm setting the grid-class attribute properly, as shown in this html snippet from my code:

```html
<chart-grid-optional ng-repeat="(id, opt) in grid.optional" axis-id="y" grid-value="0.56" grid-text="Baseline" grid-class="c3-line-baseline" class="ng-scope ng-isolate-scope"></chart-grid-optional>
```

But when I look at the actual SVG portion of the code, my grid-class isn't used at all:

```html
<g class="c3-ygrid-line"><line y2="110" y1="110" x2="426.5" x1="0" style="opacity: 1;"></line><text text-anchor="end" transform="" dx="-4" dy="-5" y="110" x="426.5" style="opacity: 1;">Baseline</text></g>
```

And for completeness, here's the CSS:

```css
.c3-line-baseline {
	stroke: red;
}
```

Can someone explain what I'm doing wrong? Or is this a bug?

**Comment by jtaylor1022** [comment]
grid-position doesn't seem to be working either:

```html
<chart-grid-optional ng-repeat="(id, opt) in grid.optional" axis-id="y" grid-value="" grid-text="Goal" grid-class="c3-line-goal" grid-position="start" class="ng-scope ng-isolate-scope"></chart-grid-optional>
```

```html
<g class="c3-ygrid-line"><line y2="221" y1="221" x2="426.5" x1="0" style="opacity: 1;"></line><text text-anchor="end" transform="" dx="-4" dy="-5" y="221" x="426.5" style="opacity: 1;">Goal</text></g>
```

The lines get drawn, they are just not styled at all. Am I missing something obvious/trivial here?

**Comment by jtaylor1022** [comment]
UPDATE: looks like these issues have been fixed in master, but have not yet been released. 

Please release 1.2 soon!

Closing.

**Comment by jettro** [comment]
Sorry you had to loose time to figure this. I draft a release as soon as possible

**Comment by jettro** [comment]
new release is available

**Comment by jtaylor1022** [comment]
Thank you very much! And thank you for all the hard work you've put into
this.

~Jason
