### ISSUE TITLE
Donut title in IE 

### ISSUE THREAD

**Issue by vinjenzo** [jettro/c3-angular-directive#110]
Hi,

I have noticed that Donut title in IE (11) is not in the middle vertically when font size is bigger than the one used also in the example page.

I tried to play with svg a bit, but no luck...

**Comment by jettro** [comment]
Would be great if you could verify this in one of the original samples at c3js.org. That way I know if I should fix it in my library or the fix should be made in the c3js library. Thanks

**Comment by vinjenzo** [comment]
You are right, the same issue is also there both in chrome and in ie, but on your example doesn`t occur in chrome, when I am changing the font size in developer tools...maybe you got some trick or idea that i could use (it seems an svg or css code may do it)

chrome OK:
![image](https://cloud.githubusercontent.com/assets/17854341/14191295/67bb0dc2-f797-11e5-8089-f3ab5ad7cff5.png)


ie:
![image](https://cloud.githubusercontent.com/assets/17854341/14191350/b8822cd6-f797-11e5-874f-71aa93a95c1c.png)


in c3js.org example the font base line stays the same on both browser, so that for bigger fonts is not vertical aligned:
![image](https://cloud.githubusercontent.com/assets/17854341/14191425/1ef52b26-f798-11e5-8741-6650d383c511.png)

**Comment by jettro** [comment]
Must be a coincidence did not really do something about it myself. Sorry.
