### ISSUE TITLE
Bug: enableZoom not working correctly with chartRegion

### ISSUE THREAD

**Issue by ashvartsman** [jettro/c3-angular-directive#114]
Hello,

When creating a line chart with regions and setting the enable-zoom property to true - on zoom functionality lines with regions don't zoom in, only the dots move. the lines without region works fine. Tested only on Chrome and FF.

Example:
![afterzoom](https://cloud.githubusercontent.com/assets/13288351/14878846/c0b5e3f0-0d2e-11e6-969e-3f716d3cac8a.png)
![beforezoom](https://cloud.githubusercontent.com/assets/13288351/14878847/c0b9878a-0d2e-11e6-894d-9d64af72b94c.png)

**Comment by jettro** [comment]
To bad the graphics you provided are not visible. Any chance of providing an online example or something? Also need to check if this is a angular lib bug or a c3js bug.
