### ISSUE TITLE
update the version on npm

### ISSUE THREAD

**Issue by kennynaoh** [jettro/c3-angular-directive#119]
Hello @jettro ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But the version on [npm](https://www.npmjs.com/package/c3-angular) is not the latest version.
Maybe should publish the latest version on npm.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/7891

**Comment by jettro** [comment]
I just uploaded version 1.2.0

**Comment by kennynaoh** [comment]
Thanks a lot
