### ISSUE TITLE
Sending HTTP request headers in C3.js to source URL

### ISSUE THREAD

**Issue by ghost** [jettro/c3-angular-directive#123]
I am trying to send http request headers (authorization header ) in c3js request.

`
$scope.config={
    bindto: '#chart1',
    data: {
        'x': 'x',
        'headers': {
            'Authorization': 'Bearer'+$rootScope.auth_token
        },
        'types': {
            'count': 'area'
        },
        'names': {
            'count': 'jobs/day'
        },
        'url': $scope.base_url,
        'mimeType': 'json'
    },
    axis: {
        x: {
            type: 'timeseries',
            tick: {
                rotate: 45,
                multiline: false,
                fit: false,
                format: $scope.format
            },
            height: 100
        }
    }
}
`
and then generating chart as 
`
  $scope.showGraph = function () {
        $scope.chart = c3.generate($scope.config);
    }`

but still headers are not being added

**Comment by jettro** [comment]
Not something I anticipated, can you check if the c3js library support something like this?
