### ISSUE TITLE
Can't use column-values="{{example}}" to update the chart

### ISSUE THREAD

**Issue by HUANGChaoLi** [jettro/c3-angular-directive#130]
Sometimes I want to update the chart by the way of angular, like 
  `c3chart(bindto-id="pie-chart{{class.id}}")
        chart-column(column-id="0-59" column-values="{{class.fail}}" column-type="pie")
        chart-column(column-id="60-100" column-values="{{class.pass}}" column-type="pie")
        chart-pie(expand="true")`.
But when I change the value of class.fail or class.pass, it doesn't work as I expected (It showed nothing). 
I can't find any example like this in [http://jettro.github.io/c3-angular-directive/#examples](http://jettro.github.io/c3-angular-directive/#examples), because it is always static value and I want dynamic value.
Could you help me to solve this problem?
Thank you so much.

**Comment by jettro** [comment]
Check the samples here:
http://jettro.github.io/c3-angular-directive/examples/index.html#/dashboard

There are a few examples that use dynamic values. Also in the other tabs than the dynamic tab.

**Comment by HUANGChaoLi** [comment]
I had seen the samples showed in [http://jettro.github.io/c3-angular-directive/examples/index.html#/dashboard](http://jettro.github.io/c3-angular-directive/examples/index.html#/dashboard) before I ask. But I can't use it in some common situations like using it in ng-repeat . 

`md-tab(label="class{{$index + 1}}" ng-repeat="class in vm.classes")
c3chart(bindto-id="pie-chart{{class.id}}", chart-data="{{class.data}}",  chart-columns="{{class.column}}")
`

I want to repeat the c3chart for every class in order to show different score distributing. But angular show error like `
Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{class.data}}] starting at [{class.data}}].
`

I think it will be very difficult to bind a variable to every chart. And I don't know if c3-angular-directive has a solution in such a situation , so I ask here.
If not, I think it will be wonderful if c3-angular-directive's data support  data-binding like angular. 
Thank you so much.
