### ISSUE TITLE
Area charts?

### ISSUE THREAD

**Issue by Perrazoo** [jettro/c3-angular-directive#165]
Thanks for your effort to make it simple the integration with angular of c3 library.

Is there any directive to create area chart?

Thanks!

**Comment by gligoran** [comment]
@Perrazoo You can use C3.js types. Try setting `column-type` to `area` or `area-spline`. (http://c3js.org/samples/chart_area_stacked.html)

**Comment by Perrazoo** [comment]
Already done! Thank you!

That comment was at the beginning with the library :)
