### ISSUE TITLE
Incorrect documentation for chartAxisXTick directive

### ISSUE THREAD

**Issue by cfsilence** [jettro/c3-angular-directive#171]
[Documentation for chartAxisXTick](http://jettro.github.io/c3-angular-directive/api-docs/1.3/chartAxisXTick.html) is incorrect for the tick-format and tick-format-time attributes.

According to [source code](https://github.com/jettro/c3-angular-directive/blob/master/c3-angular.js#L409) these attribute are named format and formatTime respectively:

![image](https://user-images.githubusercontent.com/462773/28603694-af0e9b18-7193-11e7-8711-cae63fb57b3d.png)

**Comment by jettro** [comment]
With pull request changes the parameters names to reflect what the documentation says.
