### ISSUE TITLE
Angular 1.6.6 support

### ISSUE THREAD

**Issue by alebx** [jettro/c3-angular-directive#173]
Does c3-angular work with angular 1.6.6, if so could the angular dependency bumped to 1.6.6?

**Comment by jettro** [comment]
Yes it works, you include your own version of angular, so easy to upgrade yourself. Samples now use 1.6.6

**Comment by alebx** [comment]
Thanks! It would also be nice if you could release a new version, since I'm relying on webjars I can't upgrade the version myself.

**Comment by jettro** [comment]
I will, just wanted te have some time for people to find bugs. I have integrated quite some stuff. Will try to do it before the end of the week.
