### ISSUE TITLE
Donut chart labels

### ISSUE THREAD

**Issue by theo-bittencourt** [jettro/c3-angular-directive#25]
Hi there!

I want to hide the piece's label from my donut chart, but I think it is not possible using the directives.
http://c3js.org/reference.html#donut-label-show (Docs)
http://c3js.org/samples/chart_donut.html (Example)

I'm walking through the code and can't see how to put the follow settings in  `$scope.config`:

```javascript
$scope.config.donut = {
  label: {
    show: false
  }
};
```

Nice work!  ;)

**Comment by jettro** [comment]
Fixed in master
