### ISSUE TITLE
How to remove points on line?

### ISSUE THREAD

**Issue by Lazymondaysunday** [jettro/c3-angular-directive#28]
I looked through the documentation, but didn't see how to remove points on a line graph.

**Comment by jettro** [comment]
Hi, I do not support configuring points just yet. Going to create an issue for it. Try to squeze it in the 0.4 release that I am planning on releasing at the end of the week.

**Comment by jettro** [comment]
This feature is now added to 0.4 release:

```
        <chart-points point-radius="5"
                      show-point="true"
                      point-expand-enabled="true"
                      point-expand-radius="10"/>
```
If you do not want the points, just add this sub-element to your chart.
```
        <chart-points show-point="false"/>
```
