### ISSUE TITLE
Add click event to the legend

### ISSUE THREAD

**Issue by jettro** [jettro/c3-angular-directive#29]
The legend supports events to, make it possible to register callback for at least the o'clock handler.

**Comment by eiclkun** [comment]
will this also disabled default legend.item.onclick event? the default onclick behavior on doughnut chart is really misleading.

**Comment by jettro** [comment]
Not sure, it is not really documented, but it would be logical. Will have a look at this after I finished the documentation issue.

**Comment by eiclkun** [comment]
Looks like in C3, we can disable it by assigning an empty function
<code>legend.item.onclick = function () {} 

https://github.com/masayuki0812/c3/issues/493#issuecomment-54567195

**Comment by jettro** [comment]
Fixed, also added an example to the callback example page.

**Comment by chrismfrench** [comment]
Where you do add  the following?

`legend.item.onclick = function () {} ?`
