### ISSUE TITLE
Dynamic configuration?

### ISSUE THREAD

**Issue by marcbc** [jettro/c3-angular-directive#30]
From the source code it seems that all changes possible in live graphs are only related to data. Shouldn't it be possible to also update a graph's configuration? 

For instance, I'd like to be able to change the tickFormat format based on the grouping hour/day/month, that the user is able to change by clicking a button bar. Shouldn't this config be watched as well? Is there any way to accomplish this behavior currently? 

Thanks

**Comment by jettro** [comment]
It is a nice idea, need to think about this a bit more. At the moment it is not possible,

**Comment by jettro** [comment]
I am not going to implement this in a standard way. There is however a callback mechanism that gives you the option to use the c3js api directly. Using this you can do almost all the changes that you want.
