### ISSUE TITLE
tick multiline for x-axis

### ISSUE THREAD

**Issue by shgattu** [jettro/c3-angular-directive#31]
Hi,
Is there a way I can set multiline=true in x-axis.
Couldn't find one in code.

Thanks,
Shwetha

**Comment by jettro** [comment]
In version 0.5 you can use the directive chartAxisXTick with attribute tick-multiline. Can you verify if that is what you need?

**Comment by abrararies** [comment]
@jettro is there something else we need to add besides tick-multiline. I tried adding it but it doesn't work.
I have long timestamps for my x axis ticks.

` <chart-axis-x  axis-type="timeseries"  axis-x-format="%Y-%m-%dT%H:%M:%S.%LZ">
              <chart-axis-x-tick tick-format-function="vm.tickfunc" tick-multiline="true" tick-centered="true"/>
  </chart-axis-x>`

My tick format function
`vm.tickfunc = function(timestamp){
      return d3.time.format("%Y-%m-%d (%H:%M)")(new Date(timestamp));
    }`
