### ISSUE TITLE
pie chart label format

### ISSUE THREAD

**Issue by mkovacek** [jettro/c3-angular-directive#32]
is it possible to change label format on pie chart? how to show numbers instead percentage?

**Comment by jettro** [comment]
Sorry, it took a bit longer. You can use the following sample code in the pie chart as well:
Look at the label-format-function. You might need to upgrade to the latest version of the library 0.5. This was a big addition.
```
    <c3chart bindto-id="donut-plot1-chart">
        <chart-column column-id="Data 1"
                      column-values="70"
                      column-type="donut"/>
        <chart-column column-id="Data 2"
                      column-values="35"
                      column-type="donut"/>
        <chart-column column-id="Data 3"
                      column-values="60"
                      column-type="donut"/>
        <chart-donut title="Donut" width="60" show-label="true" label-format-function="formatDonut" threshold-label="0.1"/>
    </c3chart>
```
And in the controller add:
```
    $scope.formatDonut = function (value, ratio, id) {
        return d3.format('$')(value);
    };
```

Please let me know if this is what you are looking for, than I'll close the issue

**Comment by mkovacek** [comment]
Yes that is what I looking for. On donut chart works well, but on pie chart doesn't work.

https://gist.github.com/mkovacek/41aa1ae2b262c0a3ed22

Can you put sample for pie ?

**Comment by jettro** [comment]
Your sample is looking fine, it is just that the pie was missing the formatting. I used a pull request, tested it with the donut and did not check enough if is worked for all charts. Now I added the pie in release 0.5.1. Can you please try again?

**Comment by mkovacek** [comment]
Works now.

**Comment by jettro** [comment]
Cool, thanks for reporting and testing

**Comment by Phisherman** [comment]
I'm glad that I found this issue. Shouldn't it be mentioned in the documentation?

**Comment by jettro** [comment]
I am working on API documentation, of course it will be there.

**Comment by Phisherman** [comment]
Cool!
