### ISSUE TITLE
Specifying the order of data in donut chart

### ISSUE THREAD

**Issue by Prabu-raj** [jettro/c3-angular-directive#37]
Donut chart basically sorts the data in descending order and plots. Is there any way to stop this.

**Comment by jettro** [comment]
Need to check, will let you know

**Comment by Prabu-raj** [comment]
Ok. Please let me know once done.

**Comment by Prabu-raj** [comment]
Found the way to solve it?

**Comment by jettro** [comment]
No, not yet. I cannot find an option in the c3js documentation so I is not going to be an easy fix. Would first need to be enabled in the c3js library than I can enable it in the directive.

**Comment by Prabu-raj** [comment]
Thanks for your reply

**Comment by ajagnanan** [comment]
Hello, there is an order attribute that could be set in the data property:

```
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30],
            ['data2', 120],
        ],
        order: null,  // <---this eliminates any sorting and just displays data as entered
        type : 'pie',
```

Is this possible currently? thanks.

**Comment by jettro** [comment]
Excellent find, reopened the issue and going to implement it.
http://c3js.org/reference.html#data-order

**Comment by ajagnanan** [comment]
Awesome, the 3 valid options are: "asc", "desc" and null. thanks again

**Comment by Prabu-raj** [comment]
@ajagnanan I know this solution but I need the same thing in html tags. Since I created donut chart using html tags not using the script.

**Comment by ajagnanan** [comment]
Is it possible to include this fix before the 1.0 release?

**Comment by jettro** [comment]
Hi @ajagnanan I started implementing the feature. It seems to work for the stacked bar chart. But it does not work for pie and donut. Which is weird since it uses the exact same code. If you want to try it out. I have added a property called sort-data on the c3chart directive.

**Comment by ajagnanan** [comment]
hi @jettro, the property works for me. I'm using the "null" value though, which just puts it in the order of column entry. I'm using the donut chart also.

**Comment by jettro** [comment]
Finally fixed the issue, was assigning the string null instead of actual null to the field. I have release version 0.7.0 with the fix
