### ISSUE TITLE
Interplotation doesn't work?

### ISSUE THREAD

**Issue by BobbieBarker** [jettro/c3-angular-directive#38]
Trying to make a graph using this:

    <c3chart bindto-id="donut-plot1-chart" ng-repeat="item in vm.categoricaldata">
    <chart-column column-id="{{item.name}}" column-values="{{item.value}}" column-type="donut"/>
    <chart-donut title="{{vm.selectedValue.label}}" width="70"/>
  </c3chart>

c3 chart directive doesn't seem to pick up on the interpolated values from the ng-repeat.
Is this intended behavior or am I missing something obvious?

**Comment by jettro** [comment]
It is not intended behaviour, but also not something I thought about before and I definitely did not test it. Can you try to move the ng-repeat to a div as a parent of the chart? Will do some debugging myself as well.

**Comment by valedaemon** [comment]
I'm having the same exact issue.

I did add the ng-repeat to a parent div that contains the c3chart, and it loads three donut charts. Without that though, I get an empty chart with an x-y axis displayed.

**Comment by matheusdavidson** [comment]
I had a similar problem, in my case, data was coming after an ajax call.
I think this happens because the directive expects all the data at the same time, so in your case the code will be generated and built in the loop and in my case after ajax is done.

Solution for me was placing a ```ng-if="vm.chartData"``` in ```<c3chart>``` and in my controller ```vm.chartData``` is set to ```false``` until ajax is done, then i place the result inside ```vm.chartData``` and chart is displayed correctly.

**Comment by kadinho** [comment]
@matheusdavidson work for me! Thx!

**Comment by jettro** [comment]
Having more dynamic data is supported in having dynamic column. Check the docs.

**Comment by ylligashi** [comment]
Hi guys. I am having same issue but no result to that. Can you one give me a clue.

```
<c3chart bindto-id="pie-plot1-chart" ng-if="portals" ng-repeat="portal in portals">
      <chart-column  column-id={{portal.name}}"
                    column-values="{{portal.likes / 1000}}"
                    column-type="pie"/>
    </c3chart>

```
