### ISSUE TITLE
firefix error [Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  when using with ng-hide

### ISSUE THREAD

**Issue by eiclkun** [jettro/c3-angular-directive#40]
Those charts work fine in both IE and Chrome but not in Firefox.
I am using them inside several div which i assigned ng-hide. The one shows on default is displaying but other two are not.

[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: http://123/lib/c3.min.js :: i.yForTitle :: line 3"  data: no]
http://123/c3.min.js
Line 3

**Comment by jettro** [comment]
This might be related to the c3js issue:
https://github.com/masayuki0812/c3/issues/1160

**Comment by eiclkun** [comment]
Thanks, I have reverted back to 0.4.10RC5 for now.
