### ISSUE TITLE
Make it possible to dynamically add a column

### ISSUE THREAD

**Issue by jettro** [jettro/c3-angular-directive#44]

**Comment by sajidali** [comment]
not only add a column but dynamically remove a column. I am currently working on a functionality which dynamically adds and removes a column. I have made it work to add dynamic column, but removal does not work, the column removed in code is visual still there shown in graph. :(

**Comment by rafaelmc** [comment]
I have the same problem. My data columns and data points are dynamic. If I use my chart with dynamics data columns/data points, my chart becomes unformatted. @sajidali, @jettro What do I do? Is there any way that leaves the formatted chart?

Thanks!

**Comment by jettro** [comment]
I have created a sample with the pie chart to show what you can do using callback. There was a bug in the chart to not remove old data when adding new data. Can you please check again if this problem still exists? @rafaelmc and @sajidali
