### ISSUE TITLE
Donut chart becomes a pie chart when using <chart-legend> tag

### ISSUE THREAD

**Issue by valedaemon** [jettro/c3-angular-directive#49]
Hello!

I have the following:

```javascript
<c3chart bindto-id="eventchart" chart-data="eventpoints" chart-columns="eventcolumns">
  <chart-donut expand="true" width="30" show-label="false" title="totalReports"></chart-donut>
</c3chart>
```

When I attempt to place a `<chart-legend show-legend="false">` either immediately before or after the `<chart-donut>`, the chart becomes a pie chart. Is there any way to prevent this behaviour?

Thanks!

**Comment by jettro** [comment]
Hi, I have created a sample and I cannot reproduce your problem, can you please verify the sample:
examples/donut-charts.html
