### ISSUE TITLE
can you show an example binding $scope data to a pie chart. 

### ISSUE THREAD

**Issue by skotturi** [jettro/c3-angular-directive#50]
The only example that shows data-binding makes a line graph which introduces this datax parameter. This seems crucial for an x-y graph but I cannot get a pie chart to dynamically update when the bounded data updates (and there's no datax piece because there's no x-axis)

**Comment by jettro** [comment]
I am afraid it is not possible at the moment. Will try to fix some of the issues around dynamic data the coming weeks.

**Comment by jettro** [comment]
I was to early in my judgement, this is perfectly possible. I have created a sample in the examples folder:
dynamic-pie.html

Can you try it out and let me know if this is what you need.

**Comment by dmastag** [comment]
Just tried it out for my Project. It's working perfect!

**Comment by wwagner4719** [comment]
Where is the Example of the Dynamically created PIE? I'm not seeing it in the Examples folder.

**Comment by jettro** [comment]
The best almost identical example is the gauge: http://jettro.github.io/c3-angular-directive/examples/index.html#/gauge
This contains changing data

The one I mentioned in the previous comment was this one:
http://jettro.github.io/c3-angular-directive/examples/index.html#/donut
This contains data coming from a source
