### ISSUE TITLE
We need proper documentation for the available directives and their options

### ISSUE THREAD

**Issue by jettro** [jettro/c3-angular-directive#51]
We need to create documentation for the available directives. Thinking about doing this in the site or near the source code. Not sure yet.

**Comment by jettro** [comment]
To give you an idea what I am working on:
http://jettro.github.io/c3-angular-directive/api-docs/0.7/C3jsChartDirective.html

But it is a lot of work, so it will take some time to complete it.

**Comment by dmastag** [comment]
Love how the API Docs look.

**Comment by jettro** [comment]
This issue is now done, documentation is available here:
http://jettro.github.io/c3-angular-directive/api-docs/0.7/index.html
