### ISSUE TITLE
Enable the feature to set height of x axis

### ISSUE THREAD

**Issue by carpani-mailup** [jettro/c3-angular-directive#53]
The height of x axis can be set manually by this option
http://c3js.org/reference.html#axis-x-height
It would be enough to add these lines of code within 'chartAxisX' directive
```
var height = attrs.axisHeight;
if (height) {
		axis.height = parseInt(height)};
}
```
at view side could be for example as follow:
```
<chart-axis-x axis-position="outer-center" axis-height="85"></chart-axis-x>
```

**Comment by jettro** [comment]
Fixed by the pull request, thanks
