### ISSUE TITLE
Implement Conditional Color for data

### ISSUE THREAD

**Issue by dmastag** [jettro/c3-angular-directive#56]
Is it possible to implement conditional color based on the value as per screenshot below?

![image](https://cloud.githubusercontent.com/assets/5745805/9141766/3abf44c4-3d65-11e5-8d6d-e9d23f4440c3.png)

**Comment by jettro** [comment]
There is something called the color function that should be able to do just that. Have not tried it myself. This is an example from c3:
http://c3js.org/samples/data_color.html

Will try to create a sample myself as well. Therefore will change this issue in an enhancement.

**Comment by dmastag** [comment]
Thanks for the direction. 
I saw this sample yesterday but I though it was just to have different colors for different columns. Looks like I didn't notice the different shade of blue and dark blue.

I created a working codepen for you to look at
http://codepen.io/dmastag/pen/OVqMvz

Would be great if this can be implemented into the directive.

**Comment by Phisherman** [comment]
I would appreciate that feature, too.

Seems like you slipped off in writing the directive because you linked to https://github.com/jettro/c3-angular-directive/blob/master/src/gauge-directive.js#L21 but wrote two 2 lines above about the maximum value.

**Comment by jettro** [comment]
@dmastag Hi, I know this is kind of an old issue, but maybe you still have a need. I checked your code-pen and it feels like the directive is already available in the color-directive. If you feel up te it would you like to check if that is what you need? In case of other ideas feel free to let me know.
