### ISSUE TITLE
Passing whole config object in c3chart directive

### ISSUE THREAD

**Issue by jonchenn** [jettro/c3-angular-directive#57]
It would be nice to be able to pass the entire config object from the directive for advanced setting, something like <c3chart config="myConfig"></c3chart>

So $scope.myConfig object can be defined in the Angular controller as in the samples in C3.js. e.g. http://c3js.org/samples/chart_bar_stacked.html.

Thank you! This has been a great package.

**Comment by jettro** [comment]
It is harder to decide when to start drawing the chart if I would pass the config. Should I wait before drawing or not. I made the decision to provide acces to the c3 API methods using a callback. Check this sample, maybe that is enough for you:

https://github.com/jettro/c3-angular-directive/blob/master/examples/callback-sample.html

**Comment by jonchenn** [comment]
Well, the config attribute can be pass as a base config object. Similr to the empty config object you have in controller: https://github.com/jettro/c3-angular-directive/blob/master/src/controller.js#L37. Other attributes can override the base config, and construct the final config and draw the graph as it does today.

By overriding the entire config would provide more granular control of the chart, also keep up with the latest C3 spec.

However this might be a minority use case. Feel free to close this issue if it doesn't provide too much value.

**Comment by jettro** [comment]
I would like the framework to be flexible, I understand what you mean. Going to think about it a bit more. If it helps people I wouldn't mind. Thanks for the idea

**Comment by sajidali** [comment]
@jettro I believe this suggestion will help a lot, allowing to provide base config will go a long way hopefully.

**Comment by jettro** [comment]
Fixed, you can now provide an initial c3 config object using the chart directive.

**Comment by sajidali** [comment]
Thank you @jettro

**Comment by sajidali** [comment]
URL not working any more.
"Check this sample, maybe that is enough for you:
https://github.com/jettro/c3-angular-directive/blob/master/examples/callback-sample.html"

**Comment by jettro** [comment]
You are right, did a big refactoring of the samples, you can find the running examples here:
http://jettro.github.io/c3-angular-directive/examples/index.html#/dashboard
