### ISSUE TITLE
Uncaught ReferenceError: $timeout is not defined

### ISSUE THREAD

**Issue by eiclkun** [jettro/c3-angular-directive#58]
error only occurs in min ver. <s>Maybe inline annotation is missing for $timeout?<s>

c3-angular.min.js:5
angular.module("gridshore.c3js.chart").directive("c3chart",["$timeout",C3Chart($timeout)]),angular.module("gridshore.c3js.chart").directive("chartColors",ChartColors),angular

**Comment by jettro** [comment]
Fixed the issue, everything is back to normal again
