### ISSUE TITLE
Error on creation

### ISSUE THREAD

**Issue by wester97** [jettro/c3-angular-directive#60]
I am receiving the following error:
$$.axisTimeFormat.multi is not a function

Could you guys help me troubleshoot it?  Thank you!!

TypeError: $$.axisTimeFormat.multi is not a function
    at ChartInternal.c3_chart_internal_fn.initParams (c3.js:123)
    at ChartInternal.c3_chart_internal_fn.init (c3.js:77)
    at new Chart (c3.js:34)
    at Object.c3.generate (c3.js:58)
    at showGraph (c3js-directive.js:196)
    at c3js-directive.js:498
    at angular.js:17744
    at completeOutstandingRequest (angular.js:5490)
    at angular.js:5762

**Comment by jettro** [comment]
Can you post the code somewhere?

**Comment by wester97** [comment]
I have included the necessary libraries like this:
    <script src="../bower_components/d3/d3.js"></script>
    <script src="../bower_components/c3/c3.js"></script>
    <script src="../bower_components/c3-angular/c3js-directive.js"></script>

And I'm dropping in one of the code snippets like this:
    <c3chart bindto-id="chart1">
        <chart-column column-id="data-1" 
            column-values="30,200,100,400,150,250" column-type="line"/>      
    </c3chart>

**Comment by Eden-Sun** [comment]
c3js-directive.js  is no longer used in recent versions.
you should use
```<script src="../bower_components/c3-angular/c3-angular.min.js"></script>```
and remember         ```angular.module('youAppName', ['gridshore.c3js.chart'...])```
read more about form http://jettro.github.io/c3-angular-directive/#getstarted

**Comment by wester97** [comment]
Perfect.

So, we'd need to change the bower.json file:

'"main": "c3-angular.min.js",'

**Comment by jettro** [comment]
Please let me know if it is fixed now, I created a new release 0.7.1 with the change in bower.json

**Comment by wester97** [comment]
It's alive!!  Thank you so much :)
