### ISSUE TITLE
0.7.0 build issue

### ISSUE THREAD

**Issue by ajagnanan** [jettro/c3-angular-directive#62]
Hi @jettro,

Thanks for getting this release out. Grunt wiredep is adding the c3js-directive.js (0kb) file as a dependency to the index.html with this new build. I noticed some refactoring was done and the concatenated file is not listed as the main in the bower.json [ "main": "c3js-directive.js",] file. Could you update it please?

**Comment by jettro** [comment]
I think I fixed it, created release 0.7.1
