### ISSUE TITLE
Dynamically adding data to donut

### ISSUE THREAD

**Issue by khwerhahn** [jettro/c3-angular-directive#63]
Hi,

I cannot get the last piece of the puzzle together. I have created a donut:

html
```
<c3chart bindto-id="donut-plot1-chart" chart-data="companySizeDatapoints" chart-columns="companySizeDatacolumns">
  <chart-donut title="Company Size" width="60"/>
</c3chart>
```
controller
```javascript
.controller('theCtrl', function($scope, Signup) {

    // Donut
    $scope.companySizeDatapoints = [];
    $scope.companySizeDatacolumns = [];

    Signup.graphcompanysize(function(response){
	  _.each(response,function(value,index){
		$scope.companySizeDatacolumns.push({ "id": value.category, "type": "donut", "name": value.category })
		$scope.companySizeDatapoints.push([value.category, value.percentage]);
	  })
    })
})
```

The legend with the categories are shown, but not the donut itself. What am I doing wrong?

Thx for the help!

**Comment by kunKun-tx** [comment]
@khwerhahn, i was on the same boat. the problem in your code is about that *companySizeDatapoints*
instead of 
```
$scope.companySizeDatapoints.push([value.category, value.percentage]);
```
try this:
```
var dataPoints = {};
dataPoints [value.category] = value.percentage;
$scope.companySizeDatapoints.push(dataPoints );
```

**Comment by jettro** [comment]
@khwerhahn Can you check the comment by @kunKun-tx to see if that solves your problem?

**Comment by khwerhahn** [comment]
Sorry, was busy. Just tried and it works like charm. Would be nice to see it in the docs.

thx @kunKun-tx !

**Comment by khwerhahn** [comment]
Another thing:

When I try to set the the 

```
$scope.companySizeDatapoints = [];
$scope.companySizeDatacolumns = [];
```

the donut doens't update. The previous data seems to stay. Tried already with ```$scope.$apply()```, but doens't work. 

Any thoughts?

**Comment by jettro** [comment]
I am planning on creating a sample/tutorial for dynamic pie/donut charts and see for myself what is missing. So far I did not use the dynamic part myself. Hope I can than resolve this kind of issues. 

As for your issue, could be that the binding does not like it if you assign a new array. Maybe you can set the length of the array to 0. That is what they say in this post:
http://www.2ality.com/2012/12/clear-array.html

**Comment by khwerhahn** [comment]
Cool!

Maybe this array issue could be addressed though?

**Comment by kunKun-tx** [comment]
@khwerhahn 
see the ticket i opened,
https://github.com/jettro/c3-angular-directive/issues/61
somehow ``c3-angular - v0.5.1 - 2015-06-07`` this version works.

**Comment by khwerhahn** [comment]
thx!
