### ISSUE TITLE
"tick-values" attribute for the chartAxisYTick directive not working

### ISSUE THREAD

**Issue by memo-reyes** [jettro/c3-angular-directive#64]
The tick-values attribute for the chartAxisYTick is not working as it specifies in the docs, I pass an array and it sends the following error in the console:

Error: Invalid value for <g> attribute transform="translate(0,NaN)"

I specify it like the following, in the view:
<chart-axis-y-tick tick-values="myTicks" />

In the controller:
$scope.myTicks = [1, 25, 50, ...];

which is how it is supossed to be declared according to the c3 documentation too, I also declared the values in the directive's attribute like this {{myTicks}} but it throws the same error.

**Comment by nadavivry** [comment]
I have the same problem too.

After I took a look at the source files, it seems like the directive "chartAxisXTick" is not getting the "tick-values" attribute at all, despite what it says in the documentation.

**Comment by jettro** [comment]
I fixed this issue, be sure to embed the chart-axis-y-tick directive in a chart-axis-y or else you get the message you are suggesting. Would be nice to get a better error message for this. Thinking about that one, but for now it is working. There is now also an example in the new examples folder in the project. Check the line samples.
