### ISSUE TITLE
Chart draws before data is available

### ISSUE THREAD

**Issue by wester97** [jettro/c3-angular-directive#65]
I'm fetching data, and it seems that the chart sometimes draws before the data is ready.  Could any of you help me with this?

**Comment by kunKun-tx** [comment]
http://stackoverflow.com/questions/31320401/angularjs-http-get-async-execution-order
also you might want to add a timeout function to push the data

**Comment by wester97** [comment]
I am doing an ng-repeat with data that is fetched through $resource.  Does this sound right?

**Comment by kunKun-tx** [comment]
yeah, i was doing the similar thing

**Comment by jettro** [comment]
Is this problem resolved?
