### ISSUE TITLE
How to use labels-format-function?

### ISSUE THREAD

**Issue by wjndy4** [jettro/c3-angular-directive#71]
Would you mind telling me how to use labels-format-function?
http://jettro.github.io/c3-angular-directive/api-docs/0.7/C3Chart.html
I used to use it in c3.js library easily but not for now :(

**Comment by MaphsterB** [comment]
+1 for this. An example would be useful!

Playing around with it, I finally managed to get a custom formatter to be called. The key thing I noticed is that the show-labels attribute must NOT be present on the <c3chart> tag. Here's some snippets:

```
<!-- Important: Do not put the show-labels attribute on -->
<c3chart bindto-id="chart" labels-format-function="labelFormat">
  <!-- ...More chart markup... -->
</c3chart>
```

```
// And in the controller:
$scope.labelFormat = function(v, id, i, j) {
  return "custom label format";
};
```

**Comment by tamasgal** [comment]
You can also check out my comment and marco faustinellis note on another issue: https://github.com/jettro/c3-angular-directive/issues/39#issuecomment-149528449

**Comment by wjndy4** [comment]
@MaphsterB Thank you so much for your help. It worked ^^.
@tamasgal Thank you for your suggestion :)
