### ISSUE TITLE
Group Column for a dynamic chart

### ISSUE THREAD

**Issue by oelze-cit** [jettro/c3-angular-directive#72]
Hello,

I need to use a Stacked bar chart, but my groups being dynamic values.

I have one service who give me my datapoints, datapoints and groups.

Looking at code, I can see that "addGroup" function only being used at "chartGroup Directive", and, if I use that, the groups will be static values.

I need something like this:
```
<c3chart bindto-id="chart-timeseries" chart-data="datapoints" chart-columns="datapoints" chart-x="datax" chart-group="dataGroups -> ['group1', 'group2']">
  <chart-axis-x axis-id="x" axis-type="category">
    <chart-axis-x-tick tick-rotate=90 tick-fit="false" tick-multiline="false" />
  </chart-axis-x>
  <chart-events on-click-data="ctrl.redirecionarSlaMensagensRespondidasParaAtendimentos(data)" />
</c3chart>
```

Its possible to do with actual version of directive? 

If not, looking at the code, this feature look like easy to do, only need to add ["chartGroups": "=chartGroups"] at the directive config. What you think about this feature?

**Comment by sajidali** [comment]
I am also having same issue, dynamic groups, stacks can be added or removed dynamically. but chart is not ready for this kind of requirement.

**Comment by oelze-cit** [comment]
Yes. I tried to to the modification I say in my local code and work fine. If autor prefer, I can fork and submit a pull request with this feature.

**Comment by jettro** [comment]
Pull request would be nice, I am very busy for already a few weeks, don't
see it change the coming few weeks. Need to find some time to take the
library to the next step.

On Tue, Oct 27, 2015 at 1:35 PM, oelze-cit <notifications@github.com> wrote:

> Yes. I tried to to the modification I say in my local code and work fine.
> If autor prefer, I can fork and submit a pull request with this feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jettro/c3-angular-directive/issues/72#issuecomment-151477864>
> .
>



-- 
Jettro Coenradie
http://www.gridshore.nl

**Comment by sajidali** [comment]
@oelze-cit can you quickly provide fork? I can get help from your work. I need it urgently.

**Comment by oelze-cit** [comment]
@sajidali Yes, i can work on this today. At the end of day I will open a pull request (After my work time). Can y w8ait at end of day?

**Comment by sajidali** [comment]
@oelze-cit sure :+1:

**Comment by oelze-cit** [comment]
@sajidali , sorry dude, I'm very busy yesterday. Today I will work on this feature and open a pull request as soon as I can.

**Comment by henriqueoelze** [comment]
I will work on it now. After a few minutes i will finish. (I'm oelze-cit, but this is my personal account)

**Comment by sajidali** [comment]
Waiting, hopefully it will be useful in my own use case.

**Comment by oelze-cit** [comment]
@sajidali , I'm having some problems with the feature. I add you to contribute to the repository, if can y can help contact me please :+1:

**Comment by sajidali** [comment]
@oelze-cit Added Comments in your fork.
https://github.com/henriqueoelze/c3-angular-directive/commit/faf2f0848e44780cfbefd7ef10c93590db85b206

**Comment by jettro** [comment]
Is still issue still needed? I like the idea, but I have more dynamic requests. I am thinking about a way to make this more generic.

**Comment by stevezau** [comment]
Hi, 
I have a need for a dynamic group.. I want to provide a button for stacked and unstacked..

any progress on that PR?

**Comment by jettro** [comment]
Hi @stevezau, I have created a sample using the callback function to enable or disable grouping of columns in a bar chart. Would not be to hard to add a dynamic feature for columns as well. Problem is that to make all these properties dynamic would be a lot of code. I still want to make it as easy as possible to use the basic way and make it possible to do more complex stuff as well. Let me know if this helps.
