### ISSUE TITLE
chart-bar directive examples

### ISSUE THREAD

**Issue by KrisB88** [jettro/c3-angular-directive#73]
Does anyone have an example of using the <chart-bar> directive? Looking to use this for a work project, but don't see any examples of how this should be used. Thanks!

**Comment by jettro** [comment]
Did you have a look at this?
http://jettro.github.io/c3-angular-directive/

Also in the code there is an example section with a lot of samples.

**Comment by KrisB88** [comment]
Yeah definitely. I'm trying to change the bar ratio of a chart but haven't found examples that show using the chart-bar directive anywhere. I see it for changing the ratio of a donut graph, but not for a bar graph. Sorry if I'm missing something

**Comment by jettro** [comment]
Ah, sorry, now I understand what you mean. Will add the sample to the examples folder, but this is the code:

```
<c3chart bindto-id="chart1" show-labels="true">
    <chart-column column-id="bar1"
                  column-name="Bar 1"
                  column-color="green"
                  column-values="30,200,100,400,150,250"
                  column-type="bar"/>
    <chart-bar ratio="1"/>
</c3chart>
```

**Comment by KrisB88** [comment]
Yeah that's definitely how I've been trying to use it. I guess I'm running into problems having those attributes take effect. I'm getting the same behavior with chart-donut not having any effect. I'll investigate this further and see what's going on. Thanks for your help.

**Comment by KrisB88** [comment]
I think I have solved why this isn't working for me.  The zip files on the directive size are for version 0.3.1. This caught me because we aren't using bower yet where I work. Should've just gotten then github code!  Anyways, just wanted to bring this to your attention.

**Comment by jettro** [comment]
Hmm, not sure what you mean, did I leave very old versions somewhere? Of
course not my intention, maybe I forgot something.

On Wed, Oct 28, 2015 at 3:10 AM, Kris Brown <notifications@github.com>
wrote:

> I think I have solved why this isn't working for me. The zip files on the
> directive size are for version 0.3.1. This caught me because we aren't
> using bower yet where I work. Should've just gotten then github code!
> Anyways, just wanted to bring this to your attention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jettro/c3-angular-directive/issues/73#issuecomment-151700139>
> .
>



-- 
Jettro Coenradie
http://www.gridshore.nl

**Comment by KrisB88** [comment]
The first time I got the code if was the zip file from http://jettro.github.io/c3-angular-directive/#download

**Comment by jettro** [comment]
Ah good point, will change it, thanks.

On Wed, Oct 28, 2015 at 8:17 PM, Kris Brown <notifications@github.com>
wrote:

> The first time I got the code if was the zip file from
> http://jettro.github.io/c3-angular-directive/#download
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jettro/c3-angular-directive/issues/73#issuecomment-151961830>
> .
>



-- 
Jettro Coenradie
http://www.gridshore.nl
