### ISSUE TITLE
Instead of % , how to enable exact value in pie chart tooltip

### ISSUE THREAD

**Issue by ramkibabu** [jettro/c3-angular-directive#75]
Instead of % , how to enable exact value in pie chart tooltip, can anyone pls help .

**Comment by giuseScara** [comment]
You can create your own tooltip content with exact value using c3js API:
tooltip: {
  contents: function (d, defaultTitleFormat, defaultValueFormat, color) {
    return ... // formatted html as you want
  }
}

**Comment by Sljux** [comment]
Use the [chartTooltip](http://jettro.github.io/c3-angular-directive/api-docs/0.7/chartTooltip.html) directive.

Example:

```html
<c3chart bindto-id="chart" chart-data="chartData" chart-columns="chartColumns">
    <chart-tooltip value-format-function="donutTooltipFormat"/>
</c3chart>
```

```js
$scope.chartData = [{ data1 : 30, data2 : 75, data3: 50 }];
$scope.chartColumns = [{ id : 'data1', type : 'pie' }, { id : 'data2', type : 'pie' }, { id : 'data3', type : 'pie' }];
$scope.donutTooltipFormat = function (value, ratio, id, index) {
    return value;
};
```

**Comment by ramkibabu** [comment]
Thanks Aljosa Sljuka

On Wed, Dec 16, 2015 at 6:48 PM, Aljosa Sljuka <notifications@github.com>
wrote:

> Use the chartTooltip
> <http://jettro.github.io/c3-angular-directive/api-docs/0.7/chartTooltip.html>
> directive.
>
> Example:
>
> <c3chart bindto-id="chart" chart-data="chartData" chart-columns="chartColumns">
>     <chart-tooltip value-format-function="donutTooltipFormat"/>
> </c3chart>
>
> $scope.chartData = [{ data1 : 30, data2 : 75, data3: 50 }];$scope.chartColumns = [{ id : 'data1', type : 'pie' }, { id : 'data2', type : 'pie' }, { id : 'data3', type : 'pie' }];$scope.donutTooltipFormat = function (value, ratio, id, index) {
>     return value;
> };
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jettro/c3-angular-directive/issues/75#issuecomment-165101413>
> .
>



-- 


*Regards,*

*Ramki Babu*
*Cell : 9844542655*
