### ISSUE TITLE
Different versions of minified and non minified files.

### ISSUE THREAD

**Issue by KevinHorvath** [jettro/c3-angular-directive#76]
For the working examples the c3-angular.js is version v0.5.1 while the c3-angular.min.js is v0.7.1. I was referencing the non minified version today and could not figure out why the callback was not working, but then I realized that the versions were different.

**Comment by jettro** [comment]
Hmm, strange, going to look into it. Thanks.

**Comment by jettro** [comment]
You are right, I had an idea about this some time a go, made separate grunt tasks to copy the minified and the not minified version. I do not remember why I did this so I removed it. Thanks for noticing it.
