### ISSUE TITLE
Pass a function like label format

### ISSUE THREAD

**Issue by NetanelBasal** [jettro/c3-angular-directive#77]
How can i pass a functions to the directive like label format?

```js
gauge: {
  label: {
    format: function (value, ratio) {
      return value;
    }
  }
}

```

**Comment by jettro** [comment]
Hi @NetanelBasal, You can pass a function to the directive using the attribute: label-format-function. Anything specific you'd like to accomplish?

**Comment by jtaylor1022** [comment]
Is there an example anywhere of using this directive? I haven't been able to get it to work. I'm not sure what scope the attribute is looking for the function in, but I've not been able to get it to find one either in $scope or $rootScope.

**Comment by jettro** [comment]
@jtaylor1022 Can you please check this example:
http://jettro.github.io/c3-angular-directive/examples/index.html#/donut

I am about to close this issue, if you have further questions, please use Gitter or a new issue if it does not work with wat you'd like to accomplish.
