### ISSUE TITLE
Grid Styling 

### ISSUE THREAD

**Issue by calvinKG** [jettro/c3-angular-directive#78]
1. How do you change the grid line from dots to solid line? 

2. How do you hide the x-axis line and just leave the the values 

example: 
![image](https://cloud.githubusercontent.com/assets/1926014/11474543/568d2d58-9781-11e5-83a9-00c19f177829.png)

**Comment by philskaroulis** [comment]
Try these style modifications:

// make grid lines solid
line.c3-xgrid { stroke-dasharray: none; }

// hide x axis
g.c3-axis-x path { stroke: none; }
