### ISSUE TITLE
Request: non-minified version of c3-angular

### ISSUE THREAD

**Issue by marco-faustinelli** [jettro/c3-angular-directive#84]
Currently c3-angular is distributed only in minified version. This makes it very difficult to perform any analysis of troubles.

See as example the analysis I did for issue 39, which cost me hours of pain:
https://github.com/jettro/c3-angular-directive/issues/39#issuecomment-149556437

Request is to be in condition to download also a non-minified copy of the code.

**Comment by jettro** [comment]
At the moment I ignore the non minified version. I do not really see a problem to include it. Will do that in the next release. The non minified version is in the examples folder by the way. So you can check it. Also in browsers the .map file is used to make the minified version readable again.

**Comment by jettro** [comment]
Released version 1.0.1, now with non-minified version
