### ISSUE TITLE
Donut and Pie chart column colors use the last value only

### ISSUE THREAD

**Issue by shahinlotfi** [jettro/c3-angular-directive#86]
There seems to be a bug where the color pattern values don't work for donut charts. The legend shows the correct colors, but the donut pieces all use the last color value in the pattern. The same goes for pie charts.

**Comment by anukiransolur** [comment]
I am facing the same issue too. Is there any other way to customize donut chart colors ??

**Comment by simonstewart** [comment]
Having a similar issue with wanting to specify chart colors.

I'm using the directive in this way:

<c3chart bindto-id="abc" chart-data="dataPoints" chart-columns="dataColumns">
                <chart-size chart-height="150" chart-width="150" />
                <chart-legend show-legend="false" />
                <chart-donut expand="true" width="40" show-label="false" title="" />
</c3chart>

As I'm wanting to display a separate legend, I need to specify the colors up front.

**Comment by anukiransolur** [comment]
Thanks for the reply @simonstewart . But I cant see the code because it is blank in the message.

**Comment by simonstewart** [comment]
@anukiransolur, here is is

`<c3chart bindto-id="{{dynamicId}}" chart-data="dataPoints" chart-columns="dataColumns">
                <chart-size chart-height="150" chart-width="150" />
                <chart-legend show-legend="false" />
                <chart-donut expand="true" width="40" show-label="false" title="" />
            </c3chart>`

I have tried to use the chart-colors element with a list of hex colors, but only the last color in the list is used.
Have also implemented the color-function, which gets called for each segment of the pie, but I can't seem to return a new color.

I need to be able to provide a list of colors to the chart, so I can build a separate legend with matching colors.

**Comment by anukiransolur** [comment]
@simonstewart the color function does not work. Its a bug and someone has to fix it.

**Comment by jettro** [comment]
It is fixed in the master and will be included in release 1.1

**Comment by simonstewart** [comment]
Thanks @jettro.  Seems to be fixed now.
Much appreciated.
