### ISSUE TITLE
Set initial zoom level for larger chart than is visible initially.

### ISSUE THREAD

**Issue by shahinlotfi** [jettro/c3-angular-directive#87]
I would like to add historical data to a line chart, much larger than the visible chart, and allow scrolling, much like the zoomed in view. Is this possible? If not, is there a way to set the zoom level initially?

**Comment by jettro** [comment]
Zoom is very experimental in the c3 library that I am using. At the moment I only support enabling it or not. It is also not on my shortlist to implement. If more support for it will come from the c3 library I will add it as well.
