### ISSUE TITLE
Setting Categories

### ISSUE THREAD

**Issue by stevezau** [jettro/c3-angular-directive#88]
Hi,

I can find in your api doc where we can set categories for x axis.. 

As shown in the c3 doc here http://c3js.org/samples/categorized.html

Did i miss something?

**Comment by jettro** [comment]
You can find an example on this page:

http://jettro.github.io/c3-angular-directive/examples/index.html#/bar

**Comment by nandorpersanyi** [comment]
Hi Jettro,
Really love your directives, but the docs are no too straight forward so its quite hard to figure out sometimes.
For example now I'm also struggling with this question.
How can you add category names to a dynamic c3chart directive?

**Comment by jettro** [comment]
Going to create an example to verify if this is possible
