### ISSUE TITLE
Can't create dynamic pie chart

### ISSUE THREAD

**Issue by ErezAlster** [jettro/c3-angular-directive#90]
Hi

I'm trying to feed my pie chart with dynamic controller with no success.
This is my code:
<c3chart bindto-id="pie-plot1-chart" chart-data="report" chart-columns="vm.pieColumns" >
<chart-pie expand="true"/>
</c3chart>

 $scope.vm.pieColumns = [
                {"id": "S", "type": "pie", "name": "Small" },
                {"id": "M", "type": "pie", "name": "Medium"},
                {"id": "L", "type": "pie", "name": "Large"},
                {"id": "XL", "type": "pie", "name": "Xtra Large" }
            ];

 $scope.report = { "S": 45, "M": 34, "L": 54, "XL": 11 };

do you know what can be the problem?

thanks
Erez

**Comment by jettro** [comment]
There is an example online that does just this, can you verify if that helps you with your problem?

http://jettro.github.io/c3-angular-directive/examples/index.html#/callback

**Comment by jettro** [comment]
Going to close this issue in a few weeks without additional input

**Comment by ErezAlster** [comment]
thanks a lot!
