### ISSUE TITLE
Hovering over bar chart throws error in chrome

### ISSUE THREAD

**Issue by pjindal612** [jettro/c3-angular-directive#94]
I am creating a bar chart with <chart-tooltip group-tooltip="false" />. If "group-tooltip" attribute value is false, it gives error on console "UncaughtTypeError: Cannot read property 'getItem' of undefined". If group-tooltip value is  true, it doesn't give any error.But I don't want to show any tooltips on my chart.

**Comment by jettro** [comment]
Is a problem in the c3 library:
https://github.com/masayuki0812/c3/issues/1566
