### ISSUE TITLE
Donut charts display different columns in one color when using color-pattern

### ISSUE THREAD

**Issue by pjindal612** [jettro/c3-angular-directive#97]
I want to display my charts in specific color pattern. For this, I am using below while  creating charts:
```
<chart-colors color-pattern="#5BA4B2,#157D90,#7FE2D7,#00C7B1,#91DAB9,#25B573,#FBE0A3,#EDB028,#F5C6C2,#E87B70,#E0B6C3,#BC5E7B"/>
```
Bar charts work perfectly fine but donut charts display different columns (in my case 3) with the same color. Also, it is picking the last color from the color-pattern array to display charts. It should start from the first color and display different colors for different columns. Any idea about this?

**Comment by jettro** [comment]
Which version are you using? Are you using master or a released version? I fixed a few bugs in the colours directive. Maybe I fixed your problem as well. Check the examples in the code, there are some examples now with colours. If possible show a bit more complete sample code in one of the online options than I can maybe help you better.

**Comment by asleepinglion** [comment]
Just ran into this as well. Whether I use the doughnut or regular pie charts, when using the chart-colors directive, all parts of the chart itself are the same color. The legend seems shows the correct colors, but the pie itself does not.

I'm using the latest version from master, 1.0.1 with the following chart code:

```
<c3chart bindto-id="{{chart.id}}">
    <chart-column column-id="Data 1"
                  column-values="70"
                  column-type="pie"></chart-column>
    <chart-column column-id="Data 2"
                  column-values="35"
                  column-type="pie"></chart-column>
    <chart-column column-id="Data 3"
                  column-values="60"
                  column-type="pie"></chart-column>
    <chart-pie expand="true"/>
    <chart-colors color-pattern="#1f77b4,#ffbb78,#2ca02c,#ff7f0e"></chart-colors>
  </c3chart>
```

**Comment by jettro** [comment]
Yes, sorry, did not come to a new release yet. Try to do it this week.

**Comment by jettro** [comment]
Can you please check release 1.1.0 to see if it is fixed?

**Comment by pjindal612** [comment]
This is fixed for me. But the new issue I am facing now is chart columns displayed in white color. It seems   to be broken because of while  color in donut charts.
I am using pattern like this [#5BA4B2, #157D90, #7FE2D7, #00C7B1, #91DAB9, #25B573, #FBE0A3, #EDB028, #F5C6C2, #E87B70, #E0B6C3, #BC5E7B] which  has 12 values. If number of columns/sections of chart are greater than 12, they are displayed in white color instead of repeating the pattern colors.

**Comment by jettro** [comment]
Ok, will do more investigation, a running sample with the error would be great

**Comment by jettro** [comment]
I tried it with bar charts as well as donuts and it seems to work fine. Using the release 1.3 branch. Would be nice if you could test it with the branch version, otherwise I'll close the issue and you can reopen if it does not work with 1.3 and add sample that does not work.
